[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_scm[toml]>=3.4"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "tssc/version.py"
local_scheme = "no-local-version"
version_scheme = "guess-next-dev"
