name: Publish Dev

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9' ]
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2

    - name: Set up Python 🐍
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install tox 🧰
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox

    - name: Lint Syntax 🧪🖋
      run: tox -e lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9' ]
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2

    - name: Set up Python 🐍
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install tox 🧰
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox

    - name: Test & Coverage 🧪
      run: tox -e test

    - name: Upload Coverage Report 🔺📊
      uses: codecov/codecov-action@v1
      with:
        flags: pytests
        name: Python ${{ matrix.python-version }}
        env_vars: PYTHON
        fail_ci_if_error: true

  integration-test:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Integration Tests
        env:
          OPENSHIFT_URL: ${{ secrets.OPENSHIFT_URL }}
          OPENSHIFT_USER: ${{ secrets.OPENSHIFT_USER }}
          OPENSHIFT_PASSWORD: ${{ secrets.OPENSHIFT_PASSWORD }}
          PSR_BRANCH: ${{ github.ref }}
        run: |
          ./tests/integration/run-integration-tests.sh

  build:
    needs:
    - lint
    - test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        persist-credentials: false

    - name: Set up Python 🐍
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'

    - name: Install tox 🧰
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox

    - name: Build 🛠
      run: tox -e build

    - name: Upload Distribution Artifacts 🔺
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist/

  publish:
    needs:
    - build
    runs-on: ubuntu-latest
    steps:
    - name: Download Distribution 🔻
      if: github.event_name == 'push'
      uses: actions/download-artifact@v1
      with:
        name: dist

    - name: Publish Distribution to Test PyPI 📦
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: pypa/gh-action-pypi-publish@v1.1.0
      with:
        user: __token__
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/
